# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: ki-wips
google_analytics: ki-wips
title: ki-wips

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: ki-wips

description: Stylish Jekyll Theme
author:
  name: ki-wips
  email: kiwipsco@gmail.com
  github: ki-wips
  twitter: ki-wips
  pinterest: ki-wips
  linkedin: Elena Botana de Castro
  bio: Wireless IPS
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate
